const providers = [
  { id: "apollo-chennai", name: "Apollo Hospitals International", country: "India", city: "Chennai", airport: "MAA", specialties: ["Oncology", "Cardiology", "Transplant", "Pediatrics"], rating: 4.7, reviews: 2780, cost: "high", fit: "Large international-patient desk with oncology, transplant and airport-pickup support.", website: "https://www.apollohospitals.com/", phone: "+91 4043441066", whatsapp: "+91 8076036335" },
  { id: "fortis-gurugram", name: "Fortis Memorial Research Institute", country: "India", city: "Gurugram / Delhi NCR", airport: "DEL", specialties: ["Oncology", "Neurology", "Orthopedics", "Cardiology"], rating: 4.6, reviews: 2120, cost: "high", fit: "Tertiary-care network with international coordination and doctor-opinion support.", website: "https://www.fortishealthcare.com/", phone: "+91 9266367395", whatsapp: "+91 9266367395" },
  { id: "tata-actrec", name: "Tata Memorial Centre / ACTREC", country: "India", city: "Navi Mumbai", airport: "BOM", specialties: ["Oncology", "Pediatric Cancer", "Radiation Oncology"], rating: 4.8, reviews: 1850, cost: "low", fit: "Cancer-focused public institution with research-led care and high demand.", website: "https://www.actrec.gov.in/", phone: "+91 22 27405000", whatsapp: "" },
  { id: "manipal-bengaluru", name: "Manipal Hospitals Global", country: "India", city: "Bengaluru", airport: "BLR", specialties: ["Gynecology", "Oncology", "Pediatrics", "Gastroenterology"], rating: 4.5, reviews: 1640, cost: "medium", fit: "Multi-city network with interpreters and accommodation guidance.", website: "https://www.manipalhospitalsglobal.com/", phone: "1800 102 5555", whatsapp: "" },
  { id: "cloudnine-bengaluru", name: "Cloudnine Hospitals", country: "India", city: "Bengaluru", airport: "BLR", specialties: ["Gynecology", "Maternity", "Pediatrics", "IVF"], rating: 4.5, reviews: 930, cost: "medium", fit: "Women and child care for maternity, fertility, gynecology and pediatrics.", website: "https://www.cloudninecare.com/", phone: "+91 9972499724", whatsapp: "+91 9972999729" },
  { id: "acibadem-istanbul", name: "Acibadem Healthcare Group", country: "Turkey", city: "Istanbul", airport: "IST", specialties: ["Oncology", "Cardiology", "Transplant", "Pediatrics", "Orthopedics"], rating: 4.7, reviews: 1940, cost: "high", fit: "International-patient services, airport help, interpreters and multi-specialty care.", website: "https://www.acibadem.com.tr/en/", phone: "+90 444 55 44", whatsapp: "" },
  { id: "memorial-istanbul", name: "Memorial Hospitals Group", country: "Turkey", city: "Istanbul", airport: "IST", specialties: ["Oncology", "IVF", "Cardiology", "Organ Transplant", "Orthopedics"], rating: 4.6, reviews: 1760, cost: "medium", fit: "International Patient Center for treatment planning, transfers and accommodation support.", website: "https://www.memorial.com.tr/en/", phone: "+90 549 639 3366", whatsapp: "+90 549 639 3366" },
  { id: "anadolu-kocaeli", name: "Anadolu Medical Center", country: "Turkey", city: "Kocaeli / Istanbul area", airport: "SAW", specialties: ["Oncology", "Bone Marrow Transplant", "Cardiology", "Pediatrics"], rating: 4.7, reviews: 1420, cost: "medium", fit: "Oncology-focused center with international services and on-campus accommodation options.", website: "https://www.anadolumedicalcenter.com/", phone: "+90 262 678 50 00", whatsapp: "" },
  { id: "liv-istanbul", name: "Liv Hospital", country: "Turkey", city: "Istanbul", airport: "IST", specialties: ["Oncology", "Gynecology", "Pediatrics", "Orthopedics", "Cardiology"], rating: 4.5, reviews: 1180, cost: "high", fit: "International Guest Center with WhatsApp contacts and a broad hospital network.", website: "https://www.livhospital.com/en", phone: "+90 212 999 80 99", whatsapp: "+90 530 174 33 92" },
];

const TEST_PASSCODE = "CARE-7305";
const origins = [
  { id: "LOS", label: "Lagos, Nigeria", city: "Lagos" }, { id: "ABV", label: "Abuja, Nigeria", city: "Abuja" },
  { id: "ACC", label: "Accra, Ghana", city: "Accra" }, { id: "NBO", label: "Nairobi, Kenya", city: "Nairobi" },
  { id: "JNB", label: "Johannesburg, South Africa", city: "Johannesburg" }, { id: "ADD", label: "Addis Ababa, Ethiopia", city: "Addis Ababa" },
];
const flightTemplates = [
  { airline: "Ethiopian + IndiGo", stops: "1 stop", duration: "12h 45m", minutes: 765, price: 620, tag: "Best match", aircraft: "Boeing 787 + Airbus A320", seats: "9 seats left", legs: ["LOS 13:40 - ADD 20:05", "Layover in Addis Ababa: 2h 15m", "ADD 22:20 - MAA 08:25 (+1)"] },
  { airline: "Qatar Airways", stops: "1 stop", duration: "14h 10m", minutes: 850, price: 760, tag: "Comfort pick", aircraft: "Boeing 777-300ER + Airbus A350", seats: "14 seats left", legs: ["LOS 18:35 - DOH 05:10 (+1)", "Layover in Doha: 2h 05m", "DOH 07:15 - MAA 14:45"] },
  { airline: "Emirates / partner", stops: "1 stop", duration: "15h 25m", minutes: 925, price: 830, tag: "Flexible baggage", aircraft: "Boeing 777-300ER + Boeing 737", seats: "6 seats left", legs: ["LOS 17:10 - DXB 04:45 (+1)", "Layover in Dubai: 3h 00m", "DXB 07:45 - MAA 15:35"] },
];
const turkeyFlightTemplates = [
  { airline: "Turkish Airlines", stops: "Nonstop or 1 stop", duration: "7h 05m", minutes: 425, price: 540, tag: "Fastest route", aircraft: "Airbus A330-300", seats: "11 seats left", legs: ["LOS 22:10 - IST 05:15 (+1)", "Direct service when available; confirm date in Google Flights"] },
  { airline: "Ethiopian + Turkish", stops: "1 stop", duration: "10h 30m", minutes: 630, price: 610, tag: "Best match", aircraft: "Boeing 787 + Airbus A321", seats: "8 seats left", legs: ["LOS 13:40 - ADD 20:05", "Layover in Addis Ababa: 1h 45m", "ADD 21:50 - IST 01:10 (+1)"] },
  { airline: "Qatar Airways", stops: "1 stop", duration: "12h 15m", minutes: 735, price: 720, tag: "Flexible times", aircraft: "Boeing 777-300ER + Airbus A320", seats: "16 seats left", legs: ["LOS 18:35 - DOH 05:10 (+1)", "Layover in Doha: 2h 05m", "DOH 07:15 - IST 10:50"] },
];
const stayTemplates = [
  { type: "Recovery-friendly hotel", band: "$$$", features: "Breakfast, room service, airport desk", distance: "0.8 km", rating: 4.6, rooms: "4 room types available" },
  { type: "Serviced apartment", band: "$$", features: "Kitchen, lift access, weekly rate", distance: "1.2 km", rating: 4.5, rooms: "2-bedroom and studio options" },
  { type: "Budget guest house", band: "$", features: "Caregiver bed, laundry nearby", distance: "2.4 km", rating: 4.2, rooms: "Limited accessible rooms" },
];

let state = { specialty: "All", query: "", origin: "LOS", budget: "any", country: "any", sort: "rating", flightSort: "relevance", selectedProviderId: null, selectedFlight: null, selectedStay: null, providerExpanded: false, flightExpanded: false, stayExpanded: false, view: "providers" };
const specialtySet = ["All", ...new Set(providers.flatMap((provider) => provider.specialties))];
const $ = (selector) => document.querySelector(selector);
const viewOrder = ["providers", "travel", "stays", "plan"];

function normalize(value) { return value.toLowerCase().trim(); }
function selectedProvider() { return providers.find((provider) => provider.id === state.selectedProviderId); }
function costLabel(cost) { return cost === "low" ? "Lower cost" : cost === "medium" ? "Medium cost" : "Premium cost"; }
function origin() { return origins.find((item) => item.id === state.origin); }
function visibleProviders() {
  if (state.selectedProviderId) return [selectedProvider()];
  const query = normalize(state.query); const rank = { low: 1, medium: 2, high: 3 };
  return providers.filter((provider) => (state.specialty === "All" || provider.specialties.includes(state.specialty)) && (state.budget === "any" || provider.cost === state.budget) && (state.country === "any" || provider.country === state.country) && (!query || normalize(`${provider.name} ${provider.country} ${provider.city} ${provider.specialties.join(" ")} ${provider.fit}`).includes(query))).sort((a, b) => state.sort === "cost" ? rank[a.cost] - rank[b.cost] || b.rating - a.rating : b.rating - a.rating);
}
function flightOptions() {
  const provider = selectedProvider(); if (!provider) return [];
  const templates = provider.country === "Turkey" ? turkeyFlightTemplates : flightTemplates;
  const factor = ["DEL", "IST"].includes(provider.airport) ? 0 : ["BOM", "SAW"].includes(provider.airport) ? 35 : 70;
  return templates.map((flight, index) => ({ ...flight, from: origin().id, fromCity: origin().city, to: provider.airport, price: flight.price + factor + index * 25 }));
}
function sortedFlights() {
  const options = flightOptions().map((option, index) => ({ option, index }));
  if (state.selectedFlight !== null) return options.filter((item) => item.index === state.selectedFlight);
  if (state.flightSort === "price") return options.sort((a, b) => a.option.price - b.option.price);
  if (state.flightSort === "duration") return options.sort((a, b) => a.option.minutes - b.option.minutes);
  return options;
}
function visibleStays() { return state.selectedStay === null ? stayTemplates.map((stay, index) => ({ stay, index })) : [{ stay: stayTemplates[state.selectedStay], index: state.selectedStay }]; }
function travelUrl() { const p = selectedProvider(); return `https://www.google.com/travel/flights?q=${encodeURIComponent(`Flights from ${origin().id} to ${p.airport}`)}`; }
function hotelUrl() { const p = selectedProvider(); return `https://www.google.com/travel/search?q=${encodeURIComponent(`Hotels near ${p.name}, ${p.city}, ${p.country}`)}`; }

function renderSelects() {
  $("#specialtySelect").innerHTML = specialtySet.map((specialty) => `<option value="${specialty}">${specialty === "All" ? "All specializations" : specialty}</option>`).join("");
  $("#specialtySelect").value = state.specialty;
  $("#originSelect").innerHTML = origins.map((item) => `<option value="${item.id}">${item.label}</option>`).join(""); $("#originSelect").value = state.origin;
}
function providerCard(provider) {
  const whatsapp = provider.whatsapp ? `<a class="action-link" href="https://wa.me/${provider.whatsapp.replace(/\D/g, "")}" target="_blank" rel="noreferrer">WhatsApp</a>` : `<span class="action-link secondary">WhatsApp not listed</span>`;
  const details = state.providerExpanded ? `<div class="details"><strong>Why this may fit</strong><p>${provider.fit}</p><p><strong>Nearest airport:</strong> ${provider.airport}. Ask the provider about records, visa letters, interpreters and airport transfer before travel.</p></div>` : "";
  return `<article class="card selected"><div class="card-top"><div><h3>${provider.name}</h3><div class="location">${provider.country} - ${provider.city} - nearest airport ${provider.airport}</div></div><span class="stat cost-${provider.cost}">${costLabel(provider.cost)}</span></div><p class="meta">${provider.fit}</p><div class="stat-row"><span class="stat">Rating ${provider.rating} / 5 - ${provider.reviews.toLocaleString()} reviews</span></div><div class="badges">${provider.specialties.map((item) => `<span class="badge">${item}</span>`).join("")}</div>${details}<div class="actions">${whatsapp}<a class="action-link secondary" href="tel:${provider.phone.replace(/\s/g, "")}">Call</a><a class="action-link secondary" href="${provider.website}" target="_blank" rel="noreferrer">Website</a></div><div class="choice-row"><button class="ghost-button" data-action="provider-details">${state.providerExpanded ? "Hide details" : "Explore clinic"}</button><button class="ghost-button" data-action="change-provider">Choose another clinic</button></div></article>`;
}
function renderProviders() {
  const list = visibleProviders(); $("#matchCount").textContent = state.selectedProviderId ? "Selected clinic" : `${list.length} ${list.length === 1 ? "match" : "matches"}`;
  $("#selectedProviderLabel").textContent = state.selectedProviderId ? `${selectedProvider().country} - ${selectedProvider().city}` : "Choose a clinic";
  $("#providerList").innerHTML = list.length ? list.map((provider) => state.selectedProviderId ? providerCard(provider) : `<article class="card"><div class="card-top"><div><h3>${provider.name}</h3><div class="location">${provider.country} - ${provider.city} - nearest airport ${provider.airport}</div></div><span class="stat cost-${provider.cost}">${costLabel(provider.cost)}</span></div><p class="meta">${provider.fit}</p><div class="stat-row"><span class="stat">Rating ${provider.rating} / 5 - ${provider.reviews.toLocaleString()} reviews</span></div><div class="badges">${provider.specialties.slice(0, 3).map((item) => `<span class="badge">${item}</span>`).join("")}</div><button class="primary-button full" data-provider="${provider.id}">Choose this clinic</button></article>`).join("") : `<article class="card"><h3>No exact matches</h3><p class="meta">Try another care need, country or cost preference.</p></article>`;
}
function flightCard(flight, index) {
  const detailed = state.flightExpanded && state.selectedFlight === index ? `<div class="details"><strong>Flight details</strong><p><strong>Aircraft:</strong> ${flight.aircraft}</p><p><strong>Availability:</strong> ${flight.seats}</p><ol>${flight.legs.map((leg) => `<li>${leg}</li>`).join("")}</ol><p>Times and seats are indicative. Confirm the live itinerary and fare on Google Flights before booking.</p></div>` : "";
  return `<article class="card selected"><div class="card-top"><div><h3>${flight.airline}</h3><span class="meta">${flight.tag} - ${flight.stops} - ${flight.duration}</span></div><div class="flight-price">$${flight.price}</div></div><div class="route-line"><span><strong>${flight.from}</strong>${flight.fromCity}</span><span>to</span><span><strong>${flight.to}</strong>${selectedProvider().city}</span></div>${detailed}<div class="choice-row">${state.selectedFlight === null ? `<button class="primary-button" data-flight="${index}">Choose this flight</button>` : `<button class="ghost-button" data-action="flight-details">${state.flightExpanded ? "Hide details" : "Flight details"}</button><button class="ghost-button" data-action="change-flight">Choose another flight</button>`}<a class="primary-button" href="${travelUrl()}" target="_blank" rel="noreferrer">Book on Google Flights</a></div></article>`;
}
function renderFlights() {
  const provider = selectedProvider(); if (!provider) { $("#flightContext").textContent = "Choose a clinic first to compare routes."; $("#flightList").innerHTML = ""; $("#flightBookingPanel").innerHTML = ""; return; }
  $("#flightContext").textContent = `${origin().label} to ${provider.city}, ${provider.country}, for ${provider.name}. Prices are planning estimates; live options open in Google Flights.`;
  $("#flightBookingPanel").innerHTML = `<h3>${state.selectedFlight === null ? "Compare flights" : "Your selected flight"}</h3><p>Google Flights can show current fares, airlines, luggage rules, departure times and seats for ${provider.airport}.</p>`;
  $("#flightList").innerHTML = sortedFlights().map(({ option, index }) => flightCard(option, index)).join("");
}
function stayCard(stay, index) {
  const detailed = state.stayExpanded && state.selectedStay === index ? `<div class="details"><strong>Accommodation details</strong><p><strong>Guest feedback:</strong> ${stay.rating} / 5</p><p><strong>Room availability:</strong> ${stay.rooms}</p><p>${stay.features}. Confirm room configuration, accessibility, cancellation policy and medical-caregiver needs before paying.</p></div>` : "";
  return `<article class="card selected"><div class="card-top"><div><h3>${stay.type}</h3><span class="meta">${stay.distance} from clinic - ${stay.features}</span></div><span class="stat cost-${stay.band === "$" ? "low" : stay.band === "$$" ? "medium" : "high"}">${stay.band}</span></div><div class="stat-row"><span class="stat">Guest rating ${stay.rating} / 5</span></div>${detailed}<div class="choice-row">${state.selectedStay === null ? `<button class="primary-button" data-stay="${index}">Choose this stay</button>` : `<button class="ghost-button" data-action="stay-details">${state.stayExpanded ? "Hide details" : "Stay details"}</button><button class="ghost-button" data-action="change-stay">Choose another hotel</button>`}<a class="primary-button" href="${hotelUrl()}" target="_blank" rel="noreferrer">Book on Google Hotels</a></div></article>`;
}
function renderStays() { const provider = selectedProvider(); if (!provider) { $("#stayContext").textContent = "Choose a clinic first to find accommodation."; $("#stayList").innerHTML = ""; $("#stayBookingPanel").innerHTML = ""; return; } $("#stayContext").textContent = `Accommodation near ${provider.name} in ${provider.city}, ${provider.country}.`; $("#stayBookingPanel").innerHTML = `<h3>${state.selectedStay === null ? "Compare accommodation" : "Your selected accommodation"}</h3><p>Open Google Hotels for live room availability and current booking terms.</p>`; $("#stayList").innerHTML = visibleStays().map(({ stay, index }) => stayCard(stay, index)).join(""); }
function renderPlan() { const p = selectedProvider(); const f = state.selectedFlight === null ? null : flightOptions()[state.selectedFlight]; const s = state.selectedStay === null ? null : stayTemplates[state.selectedStay]; $("#planSummary").innerHTML = `<div class="plan-item"><span>Clinic</span><strong>${p ? p.name : "Not chosen"}</strong></div><div class="plan-item"><span>Care need</span><strong>${state.specialty === "All" ? "To be confirmed" : state.specialty}</strong></div><div class="plan-item"><span>Flight</span><strong>${f ? `${f.airline}, about $${f.price}` : "Not chosen"}</strong></div><div class="plan-item"><span>Accommodation</span><strong>${s ? `${s.type}, ${s.distance}` : "Not chosen"}</strong></div>`; }
function renderFlow() { const step = viewOrder.indexOf(state.view); $("#flowProgress").textContent = `Step ${step + 1} of 4`; $("#backButton").disabled = step === 0 && !state.selectedProviderId; $("#nextButton").textContent = step === 3 ? "Review request" : "Next"; }
function renderAll() { renderSelects(); renderProviders(); renderFlights(); renderStays(); renderPlan(); renderFlow(); }
function switchView(view) { state.view = view; document.body.dataset.view = view; document.querySelectorAll(".tab, .view").forEach((node) => node.classList.remove("active")); document.querySelector(`[data-view="${view}"]`).classList.add("active"); $(`#${view}View`).classList.add("active"); renderFlow(); window.scrollTo({ top: 0, behavior: "smooth" }); }
function showToast(message) { const toast = $("#toast"); toast.textContent = message; toast.classList.add("show"); window.setTimeout(() => toast.classList.remove("show"), 3000); }
function nextStep() { if (state.view === "providers" && !state.selectedProviderId) return showToast("Choose a clinic before continuing."); if (state.view === "travel" && state.selectedFlight === null) return showToast("Choose a flight before continuing."); if (state.view === "stays" && state.selectedStay === null) return showToast("Choose accommodation before continuing."); const next = viewOrder[Math.min(viewOrder.indexOf(state.view) + 1, 3)]; switchView(next); }
function previousStep() { if (state.view === "providers" && state.selectedProviderId) { state.selectedProviderId = null; state.selectedFlight = null; state.selectedStay = null; renderAll(); showToast("You can choose a different clinic."); return; } switchView(viewOrder[Math.max(viewOrder.indexOf(state.view) - 1, 0)]); }
function setTheme() { const theme = document.body.dataset.theme === "dark" ? "light" : "dark"; document.body.dataset.theme = theme; localStorage.setItem("carebridgeTheme", theme); $("#themeButton").setAttribute("aria-label", `Switch to ${theme === "dark" ? "light" : "dark"} mode`); }

document.addEventListener("click", (event) => { const provider = event.target.closest("[data-provider]"); const flight = event.target.closest("[data-flight]"); const stay = event.target.closest("[data-stay]"); const action = event.target.closest("[data-action]"); const tab = event.target.closest("[data-view]"); if (provider) { state.selectedProviderId = provider.dataset.provider; state.selectedFlight = null; state.selectedStay = null; state.providerExpanded = false; renderAll(); showToast("Clinic selected. You can explore it or continue to flights."); } if (flight) { state.selectedFlight = Number(flight.dataset.flight); state.flightExpanded = false; renderAll(); showToast("Flight selected. Review its details or continue to hotels."); } if (stay) { state.selectedStay = Number(stay.dataset.stay); state.stayExpanded = false; renderAll(); showToast("Accommodation selected. Review it or continue to your trip."); } if (action) { if (action.dataset.action === "change-provider") { state.selectedProviderId = null; state.selectedFlight = null; state.selectedStay = null; } if (action.dataset.action === "provider-details") state.providerExpanded = !state.providerExpanded; if (action.dataset.action === "change-flight") state.selectedFlight = null; if (action.dataset.action === "flight-details") state.flightExpanded = !state.flightExpanded; if (action.dataset.action === "change-stay") state.selectedStay = null; if (action.dataset.action === "stay-details") state.stayExpanded = !state.stayExpanded; renderAll(); } if (tab) switchView(tab.dataset.view); });
$("#needSearch").addEventListener("input", (event) => { state.query = event.target.value; renderProviders(); }); $("#clearSearch").addEventListener("click", () => { state.query = ""; $("#needSearch").value = ""; renderProviders(); }); $("#specialtySelect").addEventListener("change", (event) => { state.specialty = event.target.value; renderProviders(); }); $("#originSelect").addEventListener("change", (event) => { state.origin = event.target.value; state.selectedFlight = null; renderAll(); }); $("#countrySelect").addEventListener("change", (event) => { state.country = event.target.value; renderProviders(); }); $("#budgetSelect").addEventListener("change", (event) => { state.budget = event.target.value; renderProviders(); }); $("#sortSelect").addEventListener("change", (event) => { state.sort = event.target.value; renderProviders(); }); $("#flightSortSelect").addEventListener("change", (event) => { state.flightSort = event.target.value; renderFlights(); }); $("#nextButton").addEventListener("click", nextStep); $("#backButton").addEventListener("click", previousStep); $("#themeButton").addEventListener("click", setTheme); $("#editSearchButton").addEventListener("click", () => switchView("providers"));
$("#bookingForm").addEventListener("submit", (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const p = selectedProvider(); const f = state.selectedFlight === null ? null : flightOptions()[state.selectedFlight]; const s = state.selectedStay === null ? null : stayTemplates[state.selectedStay]; if (!p || !f || !s) return showToast("Choose a clinic, flight and accommodation first."); const message = `CareBridge concierge request\nName: ${form.get("name")}\nEmail: ${form.get("email")}\nWhatsApp: ${form.get("phone")}\nClinic: ${p.name}\nFlight: ${f.airline} (${f.from}-${f.to})\nStay: ${s.type}\nNotes: ${form.get("notes") || "None"}`; const subject = encodeURIComponent("CareBridge care concierge request"); const encodedMessage = encodeURIComponent(message); window.open(`mailto:${encodeURIComponent(form.get("email"))}?subject=${subject}&body=${encodedMessage}`, "_blank"); window.open(`https://wa.me/${String(form.get("phone")).replace(/\D/g, "")}?text=${encodedMessage}`, "_blank"); showToast("Your confirmation message is ready in email and WhatsApp."); });
$("#helpButton").addEventListener("click", () => $("#helpDialog").showModal()); $("#closeHelp").addEventListener("click", () => $("#helpDialog").close()); $("#accessForm").addEventListener("submit", (event) => { event.preventDefault(); if ($("#accessCode").value.trim().toUpperCase() === TEST_PASSCODE) { localStorage.setItem("carebridgeAccess", TEST_PASSCODE); document.body.classList.remove("locked"); showToast("Access granted."); } else showToast("Passcode not recognized."); });
if (localStorage.getItem("carebridgeAccess") !== TEST_PASSCODE) document.body.classList.add("locked"); document.body.dataset.theme = "light"; document.body.dataset.view = state.view; localStorage.setItem("carebridgeTheme", "light"); renderAll();
